### ISSUE TITLE
Python auto-formatters

### ISSUE THREAD

**Issue by dgasmith** [choderalab/cookiecutter-python-comp-chem#5]
It might be good to also add support for YAPF or similar. This can be added in a `.style.yapf` file in the base folder. I typically use:

```
[style]
COLUMN_LIMIT = 119
INDENT_WIDTH = 4
USE_TABS = False
```

However, this might convolve with the usage of `pyflakes` or not.

**Comment by Lnaden** [comment]
I don't think that will be a problem with `pyflakes` since it looks for a `[flake8]` header in either a `.flake8`, `setup.cfg`, or `tox.ini` file, as I understand. I could include either a separate `tox.ini` file with the flake8 headers, or, we may even be able to do a single `setup.cfg` if we wanted to manually point all the style/test things towards it which look for `.ini` style config files

**Comment by Lnaden** [comment]
I do want to avoid the throwing the kitchen sink of config files approach though. I think this may be one area we can make a few executive choices with the cookiecutter here and use specific coverage/test/pep8 and possibly point to other options in either the output directory (maybe`devtools/README.md`) or the cookiecutter itself's README.md

**Comment by dgasmith** [comment]
Agreed that the kitchen sink is bad. More that if we suggest very specific things (like code formatting) we might want to supply the standard. 

If we go with a `setup.cfg` (which might be better) we can use the `[yapf]` heading to supply the settings.

**Comment by ctk3b** [comment]
+1 for  putting it all in `setup.cfg`
